pipeline {
    agent any
    environment {
        CHROME_BIN = credentials('chrome-binary-path')
    }
    tools {nodejs "NODEJS"}
    stages {
        stage('Security Scan') {
            steps {
                sh 'cd matador && npm audit --audit-level=critical'
            }
        }
        stage('Install') {
            steps {
                sh 'cd matador && npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'cd matador && npm run ng build'
            }
        }
        stage('Test') {
            steps {
                sh 'cd matador && CHROME_BIN="$CHROME_BIN" ng test --watch=false --browsers=ChromeHeadless'
            }
        }
    }
}