pipeline {
    agent any
    tools {nodejs "NODEJS"}
    stages {
        stage('Install') {
            steps {
                sh 'cd matador && npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'cd matador && npm run ng build'
            }
        }
    }
}