pipeline {
    agent any
    tools {nodejs "NODEJS"}
    stages {
        stage('Security Scan') {
            steps {
                sh 'cd matador && npm audit --audit-level=critical'
            }
        }
        stage('Install') {
            steps {
                sh 'cd matador && npm install'
                sh 'npm install -g @puppeteer/browsers && npx @puppeteer/browsers install chrome'
            }
        }
        stage('Build') {
            steps {
                sh 'cd matador && npm run ng build'
            }
        }
        stage('Test') {
            steps {
                sh 'cd matador && npm run test -- --watch=false --browsers=ChromeHeadless'
            }
        }
    }
}