---
config:
    class:
        hideEmptiesEnabled: true
---

classDiagram
    direction LR
    class OrderExecutor {
    }

    class OrderTopic {
        user_id: int; // partition key
    }

    class HoldingUpdater {
    }

    class CashUpdater {
    }

    class SettlementReporter {
    }

    class TradeCreator {
    }


    OrderExecutor "*" --> "*" OrderTopic : publishes
    HoldingUpdater "*" --> "*" OrderTopic : subscribes
    CashUpdater "*" --> "*" OrderTopic : subscribes
    SettlementReporter "*" --> "*" OrderTopic : subscribes
    TradeCreator "*" --> "*" OrderTopic : subscribes

    